services:
  mysqldb:
    container_name: mysqlcontainer
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

    volumes:
      - ./server/databse/dbQuery.sql:/docker-entrypoint-initdb.d/dbQuery.sql
      - ${PWD}/server/database/data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: airtribe
      MYSQL_USER: abhay
      MYSQL_PASSWORD: Abhay@123
      MYSQL_ROOT_PASSWORD: Abhay@123
      SERVICE_TAGS: dev
      Service_NAME: mysqldb
    networks:
      - airtribe-network

  server:
    container_name: servercontainer
    build: ./server
    image: server:v1 
    ports:
      - 5050:5050
    expose:
      - 5050   
    depends_on:
      - mysqldb
    environment:
      HOST: mysqldb
      DATABASE: airtribe
      USER: abhay
      PASSWORD: 'Abhay@123'
      PORT: 3306
      SERVER_PORT : 5050
      SERVICE_TAGS: dev
      Service_NAME: nodeservice
   
    networks:
      - airtribe-network

networks:
  airtribe-network:
    driver: bridge
    
